### ISSUE TITLE
Zoom in books/ articles app

### ISSUE THREAD

**Issue by loydweldy** [DefenderOfBasic/works-in-progress#9]
Is it possible to use this site to collaboratively build apps? If so should we have a formal idea pipeline?

**Comment by DefenderOfBasic** [comment]
@loydweldy yeah! could push code to the repo, or could write the code in a separate repo / glitch / codesandbox etc and do the discussion here (or over there), it all works!

(this is where I'm putting my own notes for now for this idea: https://github.com/DefenderOfBasic/works-in-progress/issues/7#issuecomment-2192488909)

**Comment by DefenderOfBasic** [comment]
the way I would build this is:

- generate the hierarchical text, given an article, use the OpenAI API or similar to convert a paragraph to a sentence, a set of paragraphs to a sentence, etc
- have some UI to zoom in (this is the part that needs some more research, could be just a simple/janky implementation to start with)

**Comment by DefenderOfBasic** [comment]
@loydweldy i'm going to close this to keep the ideas/notes around this project in the above linked ticket for now, but if you create a ticket for this in your own "works in progress" github I'd be happy to collab on a little starter kit there if you want to explore this more!
